#ifndef OOMPH_EMPTY_PLACE_HOLDER_CELL_HEADER
#define OOMPH_EMPTY_PLACE_HOLDER_CELL_HEADER

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
  #include <oomph-lib-config.h>
#endif

#include "../cell_models/cell_model_base.h"

namespace oomph
{
	class Empty_Cell : public CellModelBaseFullySegregated
	{
	public:
		Empty_Cell()
		{
			//This cell is empty
			Names_Of_Cell_Variables = { };
			Names_Of_Other_Parameters = { };
			Names_Of_Other_Variables = { };
			Names_Of_Output_Data = { };

			FinalizeConstruction();
		}

		~Empty_Cell(){ }

		double return_initial_state_variable(const unsigned &v, const unsigned &cell_type){return 0.0;}

		//Since this cell does not have any concept of what is a sensible value of membrane potential
		// it returns a Nan. This is to ensure that the user correctly handles the initial conditions
		// of this cell. If they forget or make a mistake, then the initial conditions will contian
		// nans.
		double return_initial_membrane_potential(const unsigned &cell_type){return 0.0;}

		void Calculate_Derivatives(const Boost_State_Type &Variables,
									const double &t,
									const unsigned &cell_type,
									const double &Istim,
									const Vector<double> &Other_Parameters,
									const Vector<double> &Other_Variables,
									Vector<double> &Variable_Derivatives,
									double &Iion){ }

		void get_optional_output(const Boost_State_Type &Variables,
								const double &t,
								const unsigned &cell_type,
								const double &Istim,
								const Vector<double> &Other_Parameters,
								const Vector<double> &Other_Variables,
								Vector<double> &Out){ }
	};

}

#endif