// Copyright (c) 2011-2015 by Thomas O'Hara, Yoram Rudy, 
//                            Washington University in St. Louis.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright 
// notice, this list of conditions and the following disclaimer in the 
// documentation and/or other materials provided with the distribution.
// 
// 3. Neither the names of the copyright holders nor the names of its
// contributors may be used to endorse or promote products derived from 
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
// IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
// PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
// HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
// USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF 
// THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//

// C++ Implementation of the O'Hara-Rudy dynamic (ORd) model for the
// undiseased human ventricular action potential and calcium transient
//
// The ORd model is described in the article "Simulation of the Undiseased
// Human Cardiac Ventricular Action Potential: Model Formulation and
// Experimental Validation"
// by Thomas O'Hara, Laszlo Virag, Andras Varro, and Yoram Rudy
//
// The article and supplemental materails are freely available in the
// Open Access jounal PLoS Computational Biology
// Link to Article:
// http://www.ploscompbiol.org/article/info:doi/10.1371/journal.pcbi.1002061
// 
// Email: tom.ohara@gmail.com / rudy@wustl.edu
// Web: http://rudylab.wustl.edu
// 


#ifndef OOMPH_OHARARUDY_TESTFORCE_VENT_HEADER
#define OOMPH_OHARARUDY_TESTFORCE_VENT_HEADER


// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
  #include <oomph-lib-config.h>
#endif
	
#include "../cell_models/cell_model_base.h"

namespace oomph{

class OHaraRudyTestForce : public CellModelBaseFullySegregated
{
public:
	OHaraRudyTestForce();

	~OHaraRudyTestForce();

	double return_initial_state_variable(const unsigned &v, const unsigned &cell_type);

	double return_initial_membrane_potential(const unsigned &cell_type);

	void Calculate_Derivatives(const Boost_State_Type &Variables,
														const double &t,
														const unsigned &cell_type,
														const double &Istim,
														const Vector<double> &Other_Parameters,
														const Vector<double> &Other_Variables,
														Vector<double> &Variable_Derivatives,
														double &Iion);

	void get_optional_output(const Boost_State_Type &Variables,
													const double &t,
													const unsigned &cell_type,
													const double &Istim,
													const Vector<double> &Other_Parameters,
													const Vector<double> &Other_Variables,
													Vector<double> &Out);

	enum Cell_Variables_Enum : unsigned
	{

	};
	enum Other_Parameters_Enum : unsigned
	{
		ZIndex_TT
	};
		

protected:
		//constants
		double nao;
		double cao;
		double ko;

		//buffer paramaters
		double BSRmax;
		double KmBSR;
		double BSLmax;
		double KmBSL;
		double cmdnmax;
		double kmcmdn;
		double trpnmax;
		double kmtrpn;
		double csqnmax;
		double kmcsqn;

		//CaMK paramaters
		double aCaMK;
		double bCaMK;
		double CaMKo;
		double KmCaM;
		double KmCaMK;

		//physical constants
		double R;
		double T;
		double F;

		//cell geometry
		double L;
		double rad;
		double vcell;
		double Ageo;
		double Acap;
		double vmyo;
		double vmito;
		double vsr;
		double vnsr;
		double vjsr;
		double vss;
};


} //End namespace

#endif