#ifndef OOMPH_TNNP06_FORCE_WITHOUT_ISAC_VENT_HEADER
#define OOMPH_TNNP06_FORCE_WITHOUT_ISAC_VENT_HEADER

//Totally broken

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
  #include <oomph-lib-config.h>
#endif
	
#include "../cell_models/cell_model_base.h"

namespace oomph{

class TNNP06_Force_Without_ISAC : public CellModelBaseFullyPartitioned
{
public:
	TNNP06_Force_Without_ISAC();

	~TNNP06_Force_Without_ISAC();

	double return_initial_state_variable(const unsigned &v, const unsigned &cell_type);

	double return_initial_membrane_potential(const unsigned &cell_type);


	void Calculate_Derivatives(const Boost_State_Type &Variables,
														const double &t,
														const unsigned &cell_type,
														const double &Istim,
														const Vector<double> &Other_Parameters,
														const Vector<double> &Other_Variables,
														Vector<double> &Variable_Derivatives,
														double &Iion);


	void get_optional_output(const Boost_State_Type &Variables,
													const double &t,
													const unsigned &cell_type,
													const double &Istim,
													const Vector<double> &Other_Parameters,
													const Vector<double> &Other_Variables,
													Vector<double> &Out);

	enum Cell_Variables_Enum : unsigned
	{
		cai_TT,
		CaSR_TT,
		CaSS_TT,
		Nai_TT,
		Ki_TT,
		sm_TT,
		sh_TT,
		sj_TT,
		sxr1_TT,
		sxr2_TT,
		sxs_TT,
		ss_TT,
		sr_TT,
		sd_TT,
		sf_TT,
		sf2_TT,
		sfcass_TT,
		sRR_TT,
		mNaL_TT,
		hNaL_TT,
		wt_C3_TT,
		wt_O_TT,
		wt_C1_TT,
		wt_C2_TT,
		wt_I_TT,
		N_TT,
		XBprer_TT,
		XBpostr_TT,
		SL_TT,
		xXBpostr_TT,
		xXBprer_TT,
		TRPNCaL_TT,
		TRPNCaH_TT,
		intf_TT
	};
	enum Other_Parameters_Enum : unsigned
	{
		ABIndex_TT,
		IS_Index_TT,
		RV_Index_TT
	};
		

protected:
	
	int sign(double a){ return ((a) < (0.) ? (-1.0) : (1.0));}
	double heav(double a){ return ((a) < (0.) ? (0.0) : (1.0));}
	// constants for Tent ventricle model
	//	from TNNP_MarkovIKr_function.h in haibo ni folders
	double TTCell_Ko;
	double TTCell_Cao;
	double TTCell_Nao;
	double TTCell_Vc;
	double TTCell_Vsr;
	double TTCell_Vss;
	double TTCell_Bufc;
	double TTCell_Kbufc;
	double TTCell_Bufsr;
	double TTCell_Kbufsr;
	double TTCell_Bufss;
	double TTCell_Kbufss;
	double TTCell_Vmaxup;
	double TTCell_Kup;
	double TTCell_Vrel;
	double TTCell_k1_;
	double TTCell_k2_;
	double TTCell_k3;
	double TTCell_k4;
	double TTCell_EC;
	double TTCell_maxsr;
	double TTCell_minsr;
	double TTCell_Vleak;
	double TTCell_Vxfer;
	double TTCell_R;
	double TTCell_F;
	double TTCell_T;
	double TTCell_CAPACITANCE;
	double TTCell_pKNa;
	double TTCell_GbNa;
	double TTCell_KmK;
	double TTCell_KmNa;
	double TTCell_knak;
	double TTCell_GCaL;
	double TTCell_GbCa;
	double TTCell_knaca;
	double TTCell_KmNai;
	double TTCell_KmCa;
	double TTCell_ksat;
	double TTCell_n;
	double TTCell_GpCa;
	double TTCell_KpCa;
	double TTCell_GpK;

	double TTCell_RTONF;
	double TTCell_inverseVcF2;
	double TTCell_inverseVcF;
	double TTCell_inversevssF2;

	//Rice myofilament constants
	double p0;
	double p1;
	double p2;
	double p3;
	double p4;
	double p5;
	double p6;
	double p7;
	double p8;
	// rolling back to its original value.
	double SLmax  ;
	double SLmin  ;
	double len_thin ;
	double len_thick;
	double len_hbare;
	//   Temperature Dependence
	double Qkon;
	double Qkoff;
	// double Qkoff = 1.4;
	double Qkn_p;
	double Qkp_n;
	double Qfapp;
	// double Qgapp = 6.25;
	double Qgapp;
	double Qhf;
	double Qhb;
	double Qgxb;
	//   Ca binding to troponin
	double kon    ;
	double koffL  ;
	double koffH  ;
	double perm50 ;
	double nperm  ;
	double kn_p   ;
	double kp_n   ;
	double koffmod;
	//   Thin filament regulation and crossbridge cycling
	double fapp   ;
	double gapp   ;
	double gslmod ;
	double hf     ;
	double hfmdc  ;
	double hb     ;
	double hbmdc  ;
	double gxb    ;
	double sigmap ;
	double sigman ;
	double xbmodsp;
	//   Mean strain of strongly-bound states
	double x_0    ;
	double xPsi   ;
	//   Normalized active a nd passive force
	double PCon_t ;
	double PExp_t ;
	double SL_c   ;
	double PCon_c ;
	double PExp_c ;
	//   Calculation of complete muscle response
	double massf  ;
	double visc   ;
	double KSE    ;
	double kxb    ;
	double Trop_conc;
	double Temp;

	double SLset ;         // initial length
	double SLrest;       //   (um) rest SL length for 0 passive force
	//End Rice Myofilaments constants

};


} //End namespace

#endif